@startuml
hide circle
skinparam classAttributeIconSize 0
class Dashboard {
    - expenseManager: ExpenseManager
    - eventManager: EventManager
    - fileManager: FileManager
    --
    + getExpenseManager(): ExpenseManager
    + getEventManager(): EventManager
    + getFileManager(): FileManager
}
abstract class command {
    --
    + execute(dashboard: Dashboard, ui : UI): void
}
class CategoryCommand {
    - subcommand: String
    - categoryString: String
    --
    + CategoryCommand(subcommand: String, categoryString: String)
    + CategoryCommand(subcommand: String)
    + execute(dashboard: Dashboard): void
   }
class AddCategoryFromFileCommand {
    --
    + execute(dashboard: Dashboard, ui : UI): void
}
class CategoryParser {
    + parseInput (userInput: String): Command
}
class GeneralFileParser
class Category {
     - categories: HashSet<String>
     --
     + addCategory(category: String): String
     + removeCategory(category: String): String
     + getCategoryListString(): String
}
AddCategoryFromFileCommand --|> command
CategoryCommand --|> command
Category --> "1"  Dashboard
CategoryParser -[dashed]-> CategoryCommand
CategoryCommand -[dashed]->  Category
AddCategoryFromFileCommand -[dashed]-> Category
GeneralFileParser -[dashed]-> AddCategoryFromFileCommand
@enduml